name: "[🐛]: Bug report"
about: "Отчет об ошибке. Что-то работает не так, как ожидалось."
title: "[🐛]: "
labels: [ "Status: To Do", "Priority: High" ]
projects: [ "savushkin-r-d/8" ]
type: "Bug"
assignees: KirillGutyrchik

body:
  - type: textarea
    id: bug_description
    validation: 
      required: true
    attributes:
      label: "Опишите ошибку"
      description: "Описание проблемы / скриншоты."

  - type: textarea
    id: expected_behavior
    validation: 
      required: true
    attributes:
      label: "Ожидаемое поведение"
      description: "Четкое и краткое описание того, что Вы ожидали."

  - type: textarea
    id: reproduction_steps
    validation: 
      required: true
    attributes:
      label: "Шаги для воспроизведения проблемы"
      description: "Шаги для воспроизведения проблемы."


  - type: textarea
    id: additional_info
    validation: 
      required: false
    attributes:
      label: "Дополнительная информация"
      description: "Добавьте дополнительную информацию, которая может помочь решить проблему."
