name: "[🐛]: Bug report"
description: "Отчет об ошибке. Что-то работает не так, как ожидалось."
title: "[🐛]: "
projects: [ "savushkin-r-d/8" ]
assignees: KirillGutyrchik

body:
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "Выберите приоритет задачи"
      options:
        - Low
        - Long-term plans
        - Medium
        - High
        - Critical
      default: 3
    validations:
      required: true

  - type: input
    id: desired_completion_date
    attributes:
      label: "Желаемая дата выполнения"
      description: "Укажите дату, к которой должна быть завершена задача"
      placeholder: "2026-06-30"
    validations:
      required: false

  - type: textarea
    id: bug_description
    validations: 
      required: true
    attributes:
      label: "Опишите ошибку"
      description: "Описание проблемы / скриншоты."

  - type: textarea
    id: expected_behavior
    validations: 
      required: true
    attributes:
      label: "Ожидаемое поведение"
      description: "Четкое и краткое описание того, что Вы ожидали."

  - type: textarea
    id: reproduction_steps
    validations: 
      required: true
    attributes:
      label: "Шаги для воспроизведения проблемы"
      description: "Шаги для воспроизведения проблемы."

  - type: textarea
    id: additional_info
    validations: 
      required: false
    attributes:
      label: "Дополнительная информация"
      description: "Добавьте дополнительную информацию, которая может помочь решить проблему."
