name: "[💡]: Feature request"
description: "Предложить новую функцию или улучшение."
title: "[💡]: "
projects: [ "savushkin-r-d/8" ]
assignees: KirillGutyrchik

body:
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "Выберите приоритет задачи"
      options:
        - Low
        - Long-term plans
        - Medium
        - High
        - Critical
      default: 1
    validations:
      required: true

  - type: dropdown
    id: planned_iteration
    attributes:
      label: "Планируемая итерация"
      description: "Выберите, в какой итерации должна быть задача"
      options:
        - Current sprint
        - Next sprint
        - Backlog
      default: 0
    validations:
      required: false
 
  - type: textarea
    id: feature_description
    validations: 
      required: true
    attributes:
      label: "Что бы вы хотели, чтобы было добавлено/изменено?"

  - type: textarea
    id: additional_info
    validations: 
      required: false
    attributes:
      label: "Дополнительная информация"
      description: "Добавьте дополнительную информацию или скриншоты о запросе здесь."

